# Generated by Django 4.2 on 2024-12-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture_url', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('A', models.FloatField(default=-1, null=True)),
                ('initial_portfolio', models.JSONField(default=dict)),
                ('target_portfolio', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=dict)),
                ('riskState', models.JSONField(default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
