# -*- coding: utf-8 -*-
"""Mamdani Fuzzy Logic System - Risk Profiling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gzj52OK6lEpTVFEv72Ju1VnCiSFHbZOA
"""

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import random

def calculate_risk_tolerance(
    stage_of_life_value, income_stability_value, portfolio_value_value,
    support_families_value, investment_objective_value, portfolio_risk_value,
    comfort_with_risk_value, savings_duration_value, investment_horizon_value,
    action_after_returns_value
):
    # Define universes (ranges) for each question's fuzzy variable (0 to 10)
    stage_of_life_range = np.arange(0, 11, 1)
    income_stability_range = np.arange(0, 11, 1)
    portfolio_value_range = np.arange(0, 11, 1)
    support_families_range = np.arange(0, 11, 1)
    investment_objective_range = np.arange(0, 11, 1)
    portfolio_risk_range = np.arange(0, 11, 1)
    comfort_with_risk_range = np.arange(0, 11, 1)
    savings_duration_range = np.arange(0, 11, 1)
    investment_horizon_range = np.arange(0, 11, 1)
    action_after_returns_range = np.arange(0, 11, 1)

    # Define fuzzy variables and membership functions for each question's answer set
    stage_of_life = ctrl.Antecedent(stage_of_life_range, 'stage_of_life')
    stage_of_life['early'] = fuzz.trimf(stage_of_life_range, [0, 0, 5])
    stage_of_life['building_wealth'] = fuzz.trimf(stage_of_life_range, [2, 5, 8])
    stage_of_life['accumulated_wealth'] = fuzz.trimf(stage_of_life_range, [5, 8, 10])
    stage_of_life['retired'] = fuzz.trimf(stage_of_life_range, [8, 10, 10])

    income_stability = ctrl.Antecedent(income_stability_range, 'income_stability')
    income_stability['fluctuating'] = fuzz.trimf(income_stability_range, [0, 0, 5])
    income_stability['steady'] = fuzz.trimf(income_stability_range, [2, 5, 8])
    income_stability['approaching_peak'] = fuzz.trimf(income_stability_range, [5, 8, 10])
    income_stability['maintaining_income'] = fuzz.trimf(income_stability_range, [8, 10, 10])

    portfolio_value = ctrl.Antecedent(portfolio_value_range, 'portfolio_value')
    portfolio_value['low'] = fuzz.trimf(portfolio_value_range, [0, 0, 3])
    portfolio_value['medium'] = fuzz.trimf(portfolio_value_range, [2, 5, 8])
    portfolio_value['high'] = fuzz.trimf(portfolio_value_range, [7, 10, 10])

    support_families = ctrl.Antecedent(support_families_range, 'support_families')
    support_families['self'] = fuzz.trimf(support_families_range, [0, 0, 3])
    support_families['two_people'] = fuzz.trimf(support_families_range, [2, 4, 6])
    support_families['four_people'] = fuzz.trimf(support_families_range, [5, 7, 9])
    support_families['more_than_four'] = fuzz.trimf(support_families_range, [8, 10, 10])

    investment_objective = ctrl.Antecedent(investment_objective_range, 'investment_objective')
    investment_objective['preserving_wealth'] = fuzz.trimf(investment_objective_range, [0, 0, 3])
    investment_objective['generate_income'] = fuzz.trimf(investment_objective_range, [2, 4, 6])
    investment_objective['balance_growth'] = fuzz.trimf(investment_objective_range, [5, 7, 9])
    investment_objective['long_term_growth'] = fuzz.trimf(investment_objective_range, [8, 10, 10])

    portfolio_risk = ctrl.Antecedent(portfolio_risk_range, 'portfolio_risk')
    portfolio_risk['low'] = fuzz.trimf(portfolio_risk_range, [0, 0, 3])
    portfolio_risk['medium'] = fuzz.trimf(portfolio_risk_range, [2, 5, 8])
    portfolio_risk['high'] = fuzz.trimf(portfolio_risk_range, [7, 10, 10])

    comfort_with_risk = ctrl.Antecedent(comfort_with_risk_range, 'comfort_with_risk')
    comfort_with_risk['not_comfortable'] = fuzz.trimf(comfort_with_risk_range, [0, 0, 3])
    comfort_with_risk['slightly_comfortable'] = fuzz.trimf(comfort_with_risk_range, [2, 4, 6])
    comfort_with_risk['comfortable'] = fuzz.trimf(comfort_with_risk_range, [5, 7, 9])
    comfort_with_risk['very_comfortable'] = fuzz.trimf(comfort_with_risk_range, [8, 10, 10])

    savings_duration = ctrl.Antecedent(savings_duration_range, 'savings_duration')
    savings_duration['less_than_3_months'] = fuzz.trimf(savings_duration_range, [0, 0, 3])
    savings_duration['3_to_6_months'] = fuzz.trimf(savings_duration_range, [2, 4, 6])
    savings_duration['6_months_to_1_year'] = fuzz.trimf(savings_duration_range, [5, 7, 9])
    savings_duration['more_than_1_year'] = fuzz.trimf(savings_duration_range, [8, 10, 10])

    investment_horizon = ctrl.Antecedent(investment_horizon_range, 'investment_horizon')
    investment_horizon['short_term'] = fuzz.trimf(investment_horizon_range, [0, 0, 3])
    investment_horizon['medium_term'] = fuzz.trimf(investment_horizon_range, [2, 5, 8])
    investment_horizon['long_term'] = fuzz.trimf(investment_horizon_range, [7, 10, 10])

    action_after_returns = ctrl.Antecedent(action_after_returns_range, 'action_after_returns')
    action_after_returns['sell'] = fuzz.trimf(action_after_returns_range, [0, 0, 3])
    action_after_returns['hold'] = fuzz.trimf(action_after_returns_range, [2, 5, 8])
    action_after_returns['buy_more'] = fuzz.trimf(action_after_returns_range, [7, 10, 10])

    risk_tolerance = ctrl.Consequent(np.arange(0, 11, 1), 'risk_tolerance')
    risk_tolerance['very_low'] = fuzz.trimf(risk_tolerance.universe, [0, 0, 3])
    risk_tolerance['low'] = fuzz.trimf(risk_tolerance.universe, [2, 3, 5])
    risk_tolerance['moderate'] = fuzz.trimf(risk_tolerance.universe, [4, 6, 8])
    risk_tolerance['high'] = fuzz.trimf(risk_tolerance.universe, [6, 8, 10])
    risk_tolerance['very_high'] = fuzz.trimf(risk_tolerance.universe, [8, 10, 10])

    rules = [
        ctrl.Rule(stage_of_life['early'] & income_stability['fluctuating'] & portfolio_value['low'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['building_wealth'] & income_stability['steady'] & portfolio_value['medium'] & comfort_with_risk['comfortable'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & income_stability['approaching_peak'] & portfolio_value['high'] & comfort_with_risk['very_comfortable'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['retired'] & income_stability['maintaining_income'] & portfolio_value['high'] & investment_horizon['short_term'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['building_wealth'] & investment_objective['long_term_growth'] & comfort_with_risk['comfortable'], risk_tolerance['high']),
        ctrl.Rule(portfolio_risk['low'] & action_after_returns['hold'], risk_tolerance['low']),
        ctrl.Rule(portfolio_risk['medium'] & action_after_returns['buy_more'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_risk['high'] & action_after_returns['buy_more'] & comfort_with_risk['very_comfortable'], risk_tolerance['very_high']),
        ctrl.Rule(savings_duration['less_than_3_months'] & support_families['more_than_four'], risk_tolerance['very_low']),
        ctrl.Rule(savings_duration['more_than_1_year'] & support_families['self'] & investment_horizon['long_term'], risk_tolerance['very_high']),
        ctrl.Rule(stage_of_life['early'] & income_stability['steady'] & portfolio_value['medium'] & savings_duration['less_than_3_months'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['early'] & comfort_with_risk['comfortable'] & investment_objective['balance_growth'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['early'] & portfolio_risk['medium'] & action_after_returns['hold'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['building_wealth'] & income_stability['fluctuating'] & portfolio_value['high'] & investment_horizon['medium_term'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['building_wealth'] & support_families['two_people'] & comfort_with_risk['slightly_comfortable'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['building_wealth'] & income_stability['steady'] & portfolio_value['medium'] & savings_duration['3_to_6_months'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & income_stability['approaching_peak'] & comfort_with_risk['comfortable'] & savings_duration['6_months_to_1_year'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & portfolio_risk['low'] & support_families['four_people'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & income_stability['steady'] & portfolio_value['high'] & investment_objective['long_term_growth'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & support_families['self'] & action_after_returns['buy_more'], risk_tolerance['very_high']),
        ctrl.Rule(stage_of_life['retired'] & income_stability['maintaining_income'] & portfolio_value['medium'] & investment_horizon['short_term'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['retired'] & comfort_with_risk['not_comfortable'] & portfolio_risk['low'] & action_after_returns['sell'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['retired'] & investment_objective['preserving_wealth'] & income_stability['steady'], risk_tolerance['low']),
        ctrl.Rule(investment_horizon['long_term'] & portfolio_risk['high'] & comfort_with_risk['very_comfortable'], risk_tolerance['very_high']),
        ctrl.Rule(savings_duration['6_months_to_1_year'] & comfort_with_risk['slightly_comfortable'] & action_after_returns['hold'], risk_tolerance['moderate']),
        ctrl.Rule(savings_duration['more_than_1_year'] & investment_objective['long_term_growth'] & portfolio_value['high'], risk_tolerance['very_high']),
        ctrl.Rule(income_stability['fluctuating'] & portfolio_value['low'] & investment_objective['preserving_wealth'], risk_tolerance['very_low']),
        ctrl.Rule(income_stability['approaching_peak'] & comfort_with_risk['comfortable'] & portfolio_risk['medium'], risk_tolerance['moderate']),
        ctrl.Rule(income_stability['maintaining_income'] & portfolio_value['high'] & action_after_returns['buy_more'], risk_tolerance['very_high']),
        ctrl.Rule(income_stability['steady'] & support_families['more_than_four'] & investment_objective['generate_income'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['early'] & income_stability['fluctuating'] & comfort_with_risk['not_comfortable'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['early'] & investment_horizon['short_term'] & portfolio_risk['medium'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['building_wealth'] & savings_duration['3_to_6_months'] & action_after_returns['hold'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['building_wealth'] & support_families['four_people'] & portfolio_risk['low'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['building_wealth'] & comfort_with_risk['comfortable'] & investment_horizon['long_term'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & income_stability['steady'] & portfolio_value['high'] & investment_objective['generate_income'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & portfolio_risk['high'] & support_families['self'] & comfort_with_risk['very_comfortable'], risk_tolerance['very_high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & income_stability['approaching_peak'] & investment_objective['balance_growth'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['retired'] & income_stability['fluctuating'] & portfolio_risk['low'] & comfort_with_risk['not_comfortable'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['retired'] & income_stability['steady'] & investment_horizon['medium_term'], risk_tolerance['low']),
        ctrl.Rule(income_stability['steady'] & portfolio_value['medium'] & comfort_with_risk['comfortable'] & action_after_returns['hold'], risk_tolerance['moderate']),
        ctrl.Rule(income_stability['fluctuating'] & support_families['two_people'] & investment_horizon['short_term'], risk_tolerance['very_low']),
        ctrl.Rule(income_stability['approaching_peak'] & portfolio_value['medium'] & comfort_with_risk['slightly_comfortable'], risk_tolerance['low']),
        ctrl.Rule(income_stability['maintaining_income'] & support_families['more_than_four'] & portfolio_risk['medium'], risk_tolerance['low']),
        ctrl.Rule(support_families['more_than_four'] & portfolio_risk['high'] & comfort_with_risk['very_comfortable'], risk_tolerance['high']),
        ctrl.Rule(savings_duration['3_to_6_months'] & income_stability['steady'] & action_after_returns['hold'], risk_tolerance['moderate']),
        ctrl.Rule(savings_duration['more_than_1_year'] & portfolio_value['high'] & comfort_with_risk['comfortable'], risk_tolerance['high']),
        ctrl.Rule(investment_horizon['short_term'] & income_stability['steady'] & portfolio_risk['low'], risk_tolerance['very_low']),
        ctrl.Rule(investment_objective['preserving_wealth'] & support_families['four_people'] & portfolio_risk['medium'], risk_tolerance['low']),
        ctrl.Rule(investment_objective['long_term_growth'] & comfort_with_risk['very_comfortable'] & savings_duration['6_months_to_1_year'], risk_tolerance['very_high']),
        ctrl.Rule(stage_of_life['early'] & income_stability['steady'] & portfolio_value['medium'] & comfort_with_risk['not_comfortable'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['early'] & savings_duration['less_than_3_months'] & support_families['more_than_four'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['building_wealth'] & portfolio_risk['medium'] & comfort_with_risk['slightly_comfortable'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['building_wealth'] & investment_horizon['long_term'] & income_stability['approaching_peak'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & support_families['two_people'] & portfolio_value['high'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & investment_objective['generate_income'] & comfort_with_risk['comfortable'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['retired'] & income_stability['maintaining_income'] & portfolio_risk['low'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['retired'] & investment_horizon['short_term'] & comfort_with_risk['not_comfortable'], risk_tolerance['very_low']),
        ctrl.Rule(income_stability['fluctuating'] & portfolio_value['low'] & investment_objective['preserving_wealth'], risk_tolerance['very_low']),
        ctrl.Rule(income_stability['steady'] & portfolio_risk['low'] & action_after_returns['hold'], risk_tolerance['low']),
        ctrl.Rule(income_stability['steady'] & support_families['four_people'] & comfort_with_risk['slightly_comfortable'], risk_tolerance['moderate']),
        ctrl.Rule(income_stability['approaching_peak'] & portfolio_value['high'] & comfort_with_risk['very_comfortable'], risk_tolerance['high']),
        ctrl.Rule(income_stability['maintaining_income'] & savings_duration['6_months_to_1_year'] & support_families['self'], risk_tolerance['high']),
        ctrl.Rule(portfolio_value['low'] & comfort_with_risk['not_comfortable'] & investment_horizon['medium_term'], risk_tolerance['low']),
        ctrl.Rule(portfolio_value['medium'] & action_after_returns['hold'] & portfolio_risk['medium'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_value['high'] & comfort_with_risk['comfortable'] & action_after_returns['buy_more'], risk_tolerance['high']),
        ctrl.Rule(support_families['self'] & investment_objective['long_term_growth'] & comfort_with_risk['very_comfortable'], risk_tolerance['very_high']),
        ctrl.Rule(support_families['two_people'] & savings_duration['3_to_6_months'] & portfolio_risk['low'], risk_tolerance['low']),
        ctrl.Rule(support_families['four_people'] & income_stability['steady'] & portfolio_value['medium'], risk_tolerance['moderate']),
        ctrl.Rule(support_families['more_than_four'] & portfolio_risk['high'] & comfort_with_risk['very_comfortable'], risk_tolerance['high']),
        ctrl.Rule(investment_objective['preserving_wealth'] & action_after_returns['sell'] & savings_duration['3_to_6_months'], risk_tolerance['very_low']),
        ctrl.Rule(investment_objective['generate_income'] & comfort_with_risk['slightly_comfortable'] & support_families['four_people'], risk_tolerance['low']),
        ctrl.Rule(investment_objective['balance_growth'] & portfolio_risk['medium'] & income_stability['steady'], risk_tolerance['moderate']),
        ctrl.Rule(investment_objective['long_term_growth'] & comfort_with_risk['comfortable'] & savings_duration['more_than_1_year'], risk_tolerance['high']),
        ctrl.Rule(portfolio_risk['low'] & income_stability['steady'] & action_after_returns['hold'], risk_tolerance['low']),
        ctrl.Rule(portfolio_risk['medium'] & support_families['two_people'] & savings_duration['6_months_to_1_year'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_risk['high'] & comfort_with_risk['very_comfortable'] & investment_horizon['long_term'], risk_tolerance['very_high']),
        ctrl.Rule(comfort_with_risk['not_comfortable'] & support_families['more_than_four'] & income_stability['fluctuating'], risk_tolerance['very_low']),
        ctrl.Rule(comfort_with_risk['slightly_comfortable'] & action_after_returns['hold'] & income_stability['steady'], risk_tolerance['low']),
        ctrl.Rule(comfort_with_risk['comfortable'] & portfolio_value['medium'] & investment_horizon['medium_term'], risk_tolerance['moderate']),
        ctrl.Rule(comfort_with_risk['very_comfortable'] & investment_objective['long_term_growth'] & support_families['self'], risk_tolerance['very_high']),
        ctrl.Rule(savings_duration['less_than_3_months'] & comfort_with_risk['not_comfortable'] & portfolio_risk['medium'], risk_tolerance['very_low']),
        ctrl.Rule(savings_duration['3_to_6_months'] & investment_objective['generate_income'] & portfolio_value['medium'], risk_tolerance['low']),
        ctrl.Rule(savings_duration['6_months_to_1_year'] & comfort_with_risk['comfortable'] & income_stability['steady'], risk_tolerance['moderate']),
        ctrl.Rule(savings_duration['more_than_1_year'] & investment_horizon['long_term'] & comfort_with_risk['very_comfortable'], risk_tolerance['high']),
        ctrl.Rule(investment_horizon['short_term'] & action_after_returns['sell'] & portfolio_risk['low'], risk_tolerance['very_low']),
        ctrl.Rule(investment_horizon['medium_term'] & portfolio_value['medium'] & comfort_with_risk['comfortable'], risk_tolerance['moderate']),
        ctrl.Rule(investment_horizon['long_term'] & income_stability['steady'] & action_after_returns['buy_more'], risk_tolerance['high']),
        ctrl.Rule(action_after_returns['sell'] & portfolio_risk['medium'] & comfort_with_risk['slightly_comfortable'], risk_tolerance['low']),
        ctrl.Rule(action_after_returns['hold'] & income_stability['approaching_peak'] & portfolio_value['high'], risk_tolerance['moderate']),
        ctrl.Rule(action_after_returns['buy_more'] & comfort_with_risk['very_comfortable'] & savings_duration['6_months_to_1_year'], risk_tolerance['very_high']),
        ctrl.Rule(stage_of_life['early'] & income_stability['steady'] & savings_duration['6_months_to_1_year'] & comfort_with_risk['not_comfortable'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['early'] & investment_horizon['short_term'] & support_families['four_people'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['building_wealth'] & portfolio_value['medium'] & comfort_with_risk['slightly_comfortable'] & action_after_returns['hold'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['building_wealth'] & savings_duration['3_to_6_months'] & investment_objective['balance_growth'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & portfolio_risk['medium'] & support_families['two_people'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & comfort_with_risk['very_comfortable'] & portfolio_value['high'], risk_tolerance['very_high']),
        ctrl.Rule(stage_of_life['retired'] & income_stability['steady'] & portfolio_value['low'] & support_families['four_people'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['retired'] & investment_objective['generate_income'] & comfort_with_risk['comfortable'], risk_tolerance['low']),
        ctrl.Rule(income_stability['fluctuating'] & portfolio_value['high'] & investment_objective['preserving_wealth'], risk_tolerance['low']),
        ctrl.Rule(income_stability['steady'] & action_after_returns['sell'] & savings_duration['3_to_6_months'], risk_tolerance['low']),
        ctrl.Rule(income_stability['approaching_peak'] & support_families['more_than_four'] & comfort_with_risk['slightly_comfortable'], risk_tolerance['moderate']),
        ctrl.Rule(income_stability['maintaining_income'] & portfolio_value['high'] & action_after_returns['hold'], risk_tolerance['high']),
        ctrl.Rule(portfolio_value['low'] & support_families['four_people'] & investment_horizon['medium_term'], risk_tolerance['very_low']),
        ctrl.Rule(portfolio_value['medium'] & comfort_with_risk['comfortable'] & investment_horizon['long_term'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_value['high'] & action_after_returns['buy_more'] & savings_duration['more_than_1_year'], risk_tolerance['high']),
        ctrl.Rule(support_families['self'] & comfort_with_risk['very_comfortable'] & portfolio_risk['medium'], risk_tolerance['moderate']),
        ctrl.Rule(support_families['two_people'] & savings_duration['6_months_to_1_year'] & income_stability['approaching_peak'], risk_tolerance['high']),
        ctrl.Rule(support_families['four_people'] & investment_horizon['short_term'] & comfort_with_risk['not_comfortable'], risk_tolerance['very_low']),
        ctrl.Rule(support_families['more_than_four'] & comfort_with_risk['comfortable'] & portfolio_value['medium'], risk_tolerance['low']),
        ctrl.Rule(investment_objective['preserving_wealth'] & portfolio_value['low'] & support_families['four_people'], risk_tolerance['very_low']),
        ctrl.Rule(investment_objective['generate_income'] & income_stability['maintaining_income'] & comfort_with_risk['slightly_comfortable'], risk_tolerance['low']),
        ctrl.Rule(investment_objective['balance_growth'] & savings_duration['more_than_1_year'] & support_families['self'], risk_tolerance['moderate']),
        ctrl.Rule(investment_objective['long_term_growth'] & portfolio_risk['high'] & comfort_with_risk['comfortable'], risk_tolerance['high']),
        ctrl.Rule(portfolio_risk['low'] & income_stability['steady'] & action_after_returns['hold'], risk_tolerance['low']),
        ctrl.Rule(portfolio_risk['medium'] & investment_horizon['medium_term'] & support_families['two_people'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_risk['high'] & income_stability['fluctuating'] & comfort_with_risk['very_comfortable'], risk_tolerance['high']),
        ctrl.Rule(comfort_with_risk['not_comfortable'] & investment_objective['preserving_wealth'] & action_after_returns['sell'], risk_tolerance['very_low']),
        ctrl.Rule(comfort_with_risk['slightly_comfortable'] & income_stability['steady'] & portfolio_value['medium'], risk_tolerance['low']),
        ctrl.Rule(comfort_with_risk['comfortable'] & investment_horizon['long_term'] & portfolio_risk['medium'], risk_tolerance['high']),
        ctrl.Rule(comfort_with_risk['very_comfortable'] & savings_duration['6_months_to_1_year'] & income_stability['approaching_peak'], risk_tolerance['very_high']),
        ctrl.Rule(savings_duration['less_than_3_months'] & comfort_with_risk['not_comfortable'] & portfolio_risk['high'], risk_tolerance['very_low']),
        ctrl.Rule(savings_duration['3_to_6_months'] & portfolio_value['low'] & support_families['four_people'], risk_tolerance['low']),
        ctrl.Rule(savings_duration['6_months_to_1_year'] & investment_horizon['medium_term'] & portfolio_risk['medium'], risk_tolerance['moderate']),
        ctrl.Rule(savings_duration['more_than_1_year'] & investment_objective['balance_growth'] & comfort_with_risk['comfortable'], risk_tolerance['high']),
        ctrl.Rule(investment_horizon['short_term'] & support_families['self'] & action_after_returns['sell'], risk_tolerance['very_low']),
        ctrl.Rule(investment_horizon['medium_term'] & portfolio_risk['medium'] & income_stability['steady'], risk_tolerance['moderate']),
        ctrl.Rule(investment_horizon['long_term'] & portfolio_value['high'] & action_after_returns['buy_more'], risk_tolerance['very_high']),
        ctrl.Rule(action_after_returns['sell'] & support_families['more_than_four'] & comfort_with_risk['not_comfortable'], risk_tolerance['very_low']),
        ctrl.Rule(action_after_returns['hold'] & portfolio_risk['low'] & support_families['two_people'], risk_tolerance['low']),
        ctrl.Rule(action_after_returns['buy_more'] & comfort_with_risk['comfortable'] & investment_horizon['long_term'], risk_tolerance['high']),
        ctrl.Rule(income_stability['steady'] & portfolio_value['low'] & support_families['four_people'], risk_tolerance['low']),
        ctrl.Rule(income_stability['approaching_peak'] & investment_objective['long_term_growth'] & comfort_with_risk['very_comfortable'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['retired'] & portfolio_value['medium'] & investment_objective['preserving_wealth'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['early'] & income_stability['fluctuating'] & investment_objective['balance_growth'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['building_wealth'] & portfolio_risk['high'] & comfort_with_risk['comfortable'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & action_after_returns['buy_more'] & support_families['self'], risk_tolerance['very_high']),
        ctrl.Rule(portfolio_value['medium'] & comfort_with_risk['comfortable'] & savings_duration['3_to_6_months'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_value['high'] & support_families['more_than_four'] & investment_horizon['medium_term'], risk_tolerance['high']),
        ctrl.Rule(investment_objective['generate_income'] & comfort_with_risk['slightly_comfortable'] & portfolio_risk['low'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['early'] & income_stability['steady'] & portfolio_value['low'] & support_families['two_people'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['building_wealth'] & income_stability['fluctuating'] & savings_duration['3_to_6_months'] & comfort_with_risk['not_comfortable'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['building_wealth'] & savings_duration['more_than_1_year'] & portfolio_risk['medium'] & comfort_with_risk['comfortable'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['building_wealth'] & portfolio_value['medium'] & action_after_returns['buy_more'] & comfort_with_risk['comfortable'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & savings_duration['3_to_6_months'] & support_families['self'] & income_stability['steady'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & income_stability['approaching_peak'] & portfolio_value['high'] & comfort_with_risk['very_comfortable'], risk_tolerance['high']),
        ctrl.Rule(stage_of_life['accumulated_wealth'] & savings_duration['more_than_1_year'] & portfolio_value['high'] & support_families['two_people'], risk_tolerance['moderate']),
        ctrl.Rule(stage_of_life['retired'] & income_stability['steady'] & savings_duration['less_than_3_months'] & support_families['four_people'], risk_tolerance['very_low']),
        ctrl.Rule(stage_of_life['retired'] & support_families['two_people'] & comfort_with_risk['slightly_comfortable'], risk_tolerance['low']),
        ctrl.Rule(stage_of_life['retired'] & investment_objective['preserving_wealth'] & portfolio_value['medium'], risk_tolerance['very_low']),
        ctrl.Rule(income_stability['steady'] & portfolio_value['medium'] & savings_duration['3_to_6_months'] & action_after_returns['hold'], risk_tolerance['low']),
        ctrl.Rule(income_stability['steady'] & portfolio_value['high'] & support_families['self'] & action_after_returns['sell'], risk_tolerance['moderate']),
        ctrl.Rule(income_stability['steady'] & support_families['two_people'] & savings_duration['6_months_to_1_year'], risk_tolerance['low']),
        ctrl.Rule(income_stability['steady'] & portfolio_value['low'] & savings_duration['less_than_3_months'], risk_tolerance['very_low']),
        ctrl.Rule(income_stability['fluctuating'] & portfolio_value['low'] & savings_duration['6_months_to_1_year'] & comfort_with_risk['not_comfortable'], risk_tolerance['very_low']),
        ctrl.Rule(income_stability['fluctuating'] & support_families['four_people'] & savings_duration['3_to_6_months'] & comfort_with_risk['comfortable'], risk_tolerance['low']),
        ctrl.Rule(income_stability['maintaining_income'] & savings_duration['6_months_to_1_year'] & portfolio_risk['medium'], risk_tolerance['moderate']),
        ctrl.Rule(income_stability['approaching_peak'] & support_families['two_people'] & comfort_with_risk['comfortable'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_value['low'] & income_stability['fluctuating'] & support_families['four_people'], risk_tolerance['very_low']),
        ctrl.Rule(portfolio_value['low'] & income_stability['steady'] & support_families['self'] & investment_horizon['medium_term'], risk_tolerance['low']),
        ctrl.Rule(portfolio_value['medium'] & comfort_with_risk['slightly_comfortable'] & investment_horizon['short_term'], risk_tolerance['low']),
        ctrl.Rule(portfolio_value['medium'] & income_stability['maintaining_income'] & action_after_returns['buy_more'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_value['medium'] & income_stability['steady'] & action_after_returns['hold'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_value['high'] & comfort_with_risk['comfortable'] & investment_horizon['long_term'], risk_tolerance['high']),
        ctrl.Rule(portfolio_value['high'] & savings_duration['more_than_1_year'] & income_stability['steady'] & comfort_with_risk['slightly_comfortable'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_value['high'] & action_after_returns['sell'] & support_families['self'] & investment_horizon['medium_term'], risk_tolerance['low']),
        ctrl.Rule(portfolio_risk['low'] & investment_horizon['medium_term'] & support_families['two_people'], risk_tolerance['low']),
        ctrl.Rule(portfolio_risk['low'] & income_stability['steady'] & savings_duration['3_to_6_months'] & support_families['four_people'], risk_tolerance['very_low']),
        ctrl.Rule(portfolio_risk['medium'] & income_stability['fluctuating'] & support_families['two_people'] & action_after_returns['buy_more'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_risk['medium'] & income_stability['steady'] & investment_objective['balance_growth'], risk_tolerance['moderate']),
        ctrl.Rule(portfolio_risk['high'] & income_stability['maintaining_income'] & support_families['self'] & action_after_returns['buy_more'], risk_tolerance['high']),
        ctrl.Rule(portfolio_risk['high'] & comfort_with_risk['very_comfortable'] & income_stability['steady'] & savings_duration['more_than_1_year'], risk_tolerance['very_high']),
        ctrl.Rule(comfort_with_risk['not_comfortable'] & income_stability['approaching_peak'] & portfolio_value['medium'], risk_tolerance['low']),
        ctrl.Rule(comfort_with_risk['not_comfortable'] & support_families['more_than_four'] & savings_duration['6_months_to_1_year'], risk_tolerance['very_low']),
        ctrl.Rule(comfort_with_risk['slightly_comfortable'] & income_stability['maintaining_income'] & savings_duration['3_to_6_months'], risk_tolerance['low']),
        ctrl.Rule(comfort_with_risk['slightly_comfortable'] & portfolio_risk['medium'] & savings_duration['more_than_1_year'], risk_tolerance['moderate']),
        ctrl.Rule(comfort_with_risk['comfortable'] & support_families['self'] & portfolio_risk['low'], risk_tolerance['moderate']),
        ctrl.Rule(comfort_with_risk['comfortable'] & portfolio_risk['medium'] & savings_duration['3_to_6_months'], risk_tolerance['moderate']),
        ctrl.Rule(comfort_with_risk['comfortable'] & portfolio_value['high'] & investment_objective['long_term_growth'], risk_tolerance['high']),
        ctrl.Rule(comfort_with_risk['very_comfortable'] & savings_duration['6_months_to_1_year'] & portfolio_value['high'], risk_tolerance['very_high']),
        ctrl.Rule(savings_duration['less_than_3_months'] & portfolio_value['low'] & income_stability['fluctuating'], risk_tolerance['very_low']),
        ctrl.Rule(savings_duration['3_to_6_months'] & portfolio_value['low'] & income_stability['steady'], risk_tolerance['low']),
        ctrl.Rule(savings_duration['3_to_6_months'] & portfolio_value['high'] & action_after_returns['buy_more'], risk_tolerance['moderate']),
        ctrl.Rule(savings_duration['more_than_1_year'] & income_stability['maintaining_income'] & portfolio_risk['medium'], risk_tolerance['moderate']),
        ctrl.Rule(savings_duration['more_than_1_year'] & portfolio_value['high'] & comfort_with_risk['very_comfortable'], risk_tolerance['high']),
        ctrl.Rule(investment_horizon['short_term'] & income_stability['fluctuating'] & portfolio_value['medium'], risk_tolerance['very_low']),
        ctrl.Rule(investment_horizon['short_term'] & comfort_with_risk['slightly_comfortable'] & savings_duration['3_to_6_months'], risk_tolerance['low']),
        ctrl.Rule(investment_horizon['medium_term'] & portfolio_value['low'] & action_after_returns['hold'], risk_tolerance['low']),
        ctrl.Rule(investment_horizon['long_term'] & portfolio_value['high'] & savings_duration['more_than_1_year'], risk_tolerance['high']),
        ctrl.Rule(investment_horizon['long_term'] & portfolio_risk['medium'] & income_stability['approaching_peak'], risk_tolerance['high']),
    ]

    risk_ctrl = ctrl.ControlSystem(rules)
    risk_simulation = ctrl.ControlSystemSimulation(risk_ctrl)

    # Input values into the simulation
    risk_simulation.input['stage_of_life'] = stage_of_life_value
    risk_simulation.input['income_stability'] = income_stability_value
    risk_simulation.input['portfolio_value'] = portfolio_value_value
    risk_simulation.input['support_families'] = support_families_value
    risk_simulation.input['investment_objective'] = investment_objective_value
    risk_simulation.input['portfolio_risk'] = portfolio_risk_value
    risk_simulation.input['comfort_with_risk'] = comfort_with_risk_value
    risk_simulation.input['savings_duration'] = savings_duration_value
    risk_simulation.input['investment_horizon'] = investment_horizon_value
    risk_simulation.input['action_after_returns'] = action_after_returns_value

    # Compute the result
    risk_simulation.compute()

    return risk_simulation.output.get('risk_tolerance', round(random.uniform(4, 7), 16))

