# Generated by Django 5.1.4 on 2024-12-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
